export { add, type AddOptions, type AddResult } from './add.js'
export {
  CONFIG_FILE,
  ConfigSchema,
  DEFAULT_CONFIG,
  aliasKeyOf,
  readConfig,
  targetDir,
  writeConfig,
  type Config,
} from './config.js'
export { rewriteImports } from './rewrite.js'
export { formatProductList } from './product-list.js'
export {
  CopiedArtifactSchema,
  ComposedPresentationCoverageSchema,
  MachineFreeSchema,
  NotApplicablePresentationCoverageSchema,
  PartialPresentationCoverageSchema,
  PresentationCoverageSchema,
  PresentationFamilySchema,
  ProductAliasSchema,
  ProductContractError,
  ProductCategorySchema,
  ProductContractSchema,
  ProductEntrySchema,
  ProductPresentationSchema,
  PublicMachineSchema,
  StyledPresentationCoverageSchema,
  StylelessPresentationCoverageSchema,
  StylingSupportSchema,
  parseProductContract,
  resolveCopiedArtifact,
  resolveProductIdentity,
  type CopiedArtifact,
  type ComposedPresentationCoverage,
  type MachineFree,
  type NotApplicablePresentationCoverage,
  type PartialPresentationCoverage,
  type PresentationCoverage,
  type PresentationFamily,
  type ProductAlias,
  type ProductCategory,
  type ProductContract,
  type ProductEntry,
  type ProductPresentation,
  type PublicMachine,
  type ResolvedCopiedArtifact,
  type ResolvedProductIdentity,
  type StyledPresentationCoverage,
  type StylelessPresentationCoverage,
  type StylingSupport,
} from './product-contract.js'
export {
  LLUI_SCOPE,
  RegistryFileSchema,
  RegistryItemSchema,
  RegistrySchema,
  WORKSPACE_SPEC,
  assertDependencySpecs,
  assertSafeTarget,
  collectDependencies,
  isRemote,
  loadRegistry,
  loadRemoteItem,
  parseDependencySpec,
  resolveItems,
  type DependencyRequirement,
  type Registry,
  type RegistryFile,
  type RegistryItem,
} from './registry.js'
export { compareVersions, minimumOfRange, parseVersion, type Version } from './semver.js'
export {
  VersionMismatchError,
  checkVersions,
  findInstalled,
  projectVersion,
  type ProjectVersion,
  type VersionCheck,
  type VersionMismatch,
  type VersionStatus,
} from './versions.js'
