#!/usr/bin/env -S node --experimental-strip-types --no-warnings
// Generate `docs/designs/14 Compile-Time Rules.md` from the compiler's
// always-on lint modules.
//
// Reads the rule list directly from `createLintModules()` — the single
// source of truth `transform.ts` also uses. Adding or removing a rule
// in `packages/compiler/src/lint-modules.ts` updates both the build
// pipeline and this doc on the next regeneration.
//
// Re-run when rules change: `pnpm tsx scripts/generate-rule-docs.ts`.

import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { createLintModules } from '../packages/compiler/src/lint-modules.js'
import { compilerStampModule } from '../packages/compiler/src/modules/compiler-stamp.js'

// `compilerStampModule` is always-on too (the integrity marker) but
// lives outside `createLintModules` because it's an instance rather
// than a factory. Include it here so the doc is complete.
const allModules = [compilerStampModule, ...createLintModules()]

interface RuleRow {
  id: string
  description: string
  category: string
}

const rows: RuleRow[] = []
for (const m of allModules) {
  for (const d of m.diagnostics ?? []) {
    rows.push({ id: d.id, description: d.description, category: 'unknown' })
  }
}

// Categories aren't carried by `DiagnosticDefinition` itself (only the
// per-call `Diagnostic` instance carries `category`). Hand-mapped here
// — a small, stable table. Mismatches surface as "uncategorized" in
// the rendered output.
const RULE_CATEGORIES: Record<string, string> = {
  'llui/compiler-version': 'config',
  'llui/bitmask-overflow': 'perf',
  'llui/async-update': 'reactivity',
  'llui/map-on-state-array': 'reactivity',
  'llui/nested-send-in-update': 'reactivity',
  'llui/direct-state-in-view': 'reactivity',
  'llui/imperative-dom-in-view': 'reactivity',
  'llui/accessor-side-effect': 'reactivity',
  'llui/state-mutation': 'reactivity',
  'llui/effect-without-handler': 'composition',
  'llui/exhaustive-effect-handling': 'composition',
  'llui/no-eager-item-accessor': 'reactivity',
  'llui/pure-update-function': 'reactivity',
  'llui/exhaustive-update': 'reactivity',
  'llui/no-let-reactive-accessor': 'reactivity',
  'llui/each-closure-violation': 'reactivity',
  'llui/string-effect-callback': 'agent',
  'llui/agent-missing-intent': 'agent',
  'llui/agent-warning-on-confirm': 'agent',
  'llui/agent-example-on-payload': 'agent',
  'llui/agent-exclusive-annotations': 'agent',
  'llui/agent-optional-field-undocumented': 'agent',
  'llui/agent-tagsend-translator-missing': 'agent',
  'llui/agent-nonextractable-handler': 'agent',
  'llui/agent-emits-drift': 'agent',
  'llui/agent-msg-resolvable': 'agent',
  'llui/subapp-requires-reason': 'composition',
  'llui/empty-props': 'style',
  'llui/forgotten-spread': 'composition',
  'llui/accessibility': 'style',
  'llui/view-bag-import': 'style',
  'llui/controlled-input': 'composition',
  'llui/missing-memo': 'perf',
  'llui/namespace-import': 'style',
  'llui/no-barrel-import-when-subpath-exists': 'perf',
  'llui/form-boilerplate': 'style',
  'llui/spread-in-children': 'perf',
  'llui/static-items': 'reactivity',
  'llui/static-on': 'reactivity',
  'llui/no-list-render-in-sample': 'reactivity',
  'llui/no-sample-in-accessor': 'reactivity',
  'llui/no-sample-in-reactive-position': 'reactivity',
}

for (const r of rows) r.category = RULE_CATEGORIES[r.id] ?? 'unknown'

const uncategorized = rows.filter((r) => r.category === 'unknown')
if (uncategorized.length > 0) {
  console.error(
    `⚠ ${uncategorized.length} rule(s) missing from RULE_CATEGORIES — they'll render under "unknown":`,
  )
  for (const r of uncategorized) console.error(`  - ${r.id}`)
}

// Group + render.
const byCategory = new Map<string, RuleRow[]>()
for (const r of rows) {
  const list = byCategory.get(r.category) ?? []
  list.push(r)
  byCategory.set(r.category, list)
}
for (const list of byCategory.values()) list.sort((a, b) => a.id.localeCompare(b.id))

const CATEGORY_ORDER = ['reactivity', 'composition', 'agent', 'perf', 'style', 'config', 'unknown']
const CATEGORY_BLURBS: Record<string, string> = {
  reactivity:
    'Catch patterns that silently break reactivity — stale captures, side effects in accessors, missing reconciliation, impure reducers.',
  composition:
    'Catch composition mistakes — broken structural primitives, missing handlers, wrong arrangement of view-tree pieces.',
  agent:
    'Enforce the agent-protocol annotation discipline so `list_actions` surfaces a coherent affordance set to Claude.',
  perf: 'Catch patterns that disable compile-time optimizations or scale poorly at runtime.',
  style:
    "Style nudges that don't change behavior but make code easier to read, review, and tree-shake.",
  config: 'Build-pipeline integrity — the compiler did its job.',
  unknown: 'Uncategorized rules (this section should be empty in steady state).',
}

let md =
  `# 14. Compile-Time Rules\n\n` +
  `> **Auto-generated by \`scripts/generate-rule-docs.ts\`.** Re-run after rule changes:\n` +
  `> \`pnpm tsx scripts/generate-rule-docs.ts\`\n>\n` +
  `> Single source of truth: \`packages/compiler/src/lint-modules.ts\`. Adding or removing a rule there propagates to both the transform pipeline and this doc.\n\n` +
  `Every rule listed here fires as a **compile-time error** from \`@llui/compiler\`, surfaced by \`@llui/vite-plugin\`'s build pipeline as \`this.error(…)\`. There is no warning tier; an LLM-first authoring loop treats anything else as ignorable noise.\n\n` +
  `Total: **${rows.length}** rules.\n\n` +
  `## Categories\n\n`

for (const cat of CATEGORY_ORDER) {
  const list = byCategory.get(cat)
  if (!list || list.length === 0) continue
  md += `### \`${cat}\` (${list.length})\n\n`
  md += `${CATEGORY_BLURBS[cat]}\n\n`
  md += `| Rule | Description |\n`
  md += `| --- | --- |\n`
  for (const r of list) {
    const idCell = '`' + r.id + '`'
    const descCell = r.description.replace(/\|/g, '\\|')
    md += `| ${idCell} | ${descCell} |\n`
  }
  md += `\n`
}

md +=
  `## Rule severity\n\n` +
  `All compile-time rules emit at \`severity: 'error'\`. The LLui project's stance: warnings get reported and never fixed, so anything ship-worthy enough to ship at all ships as an error.\n\n` +
  `Adapters (e.g. \`@llui/vite-plugin\`) may downgrade to warnings on a per-host basis if needed (see \`Diagnostic.severity\` for the intent the rule itself emits). The vite-plugin currently calls \`this.error()\` for \`error\`, \`this.warn()\` for \`warning\`.\n\n` +
  `## Cross-file coverage\n\n` +
  `The agent rules (\`agent-emits-drift\`, \`agent-msg-resolvable\`) read imported \`Msg\` unions when the host adapter supplies the cross-file source via \`typeSources.msg\`. The vite-plugin does this automatically. Tests that invoke \`transformLlui\` directly without \`typeSources\` fall back to file-local-only behaviour.\n`

writeFileSync(resolve('docs/designs/14 Compile-Time Rules.md'), md)
console.log(
  `Wrote docs/designs/14 Compile-Time Rules.md — ${rows.length} rules across ${byCategory.size} categories.`,
)
