export * as agentAttention from './agentAttention.js'
export * as agentConnect from './agentConnect.js'
export * as agentConfirm from './agentConfirm.js'
export * as agentLog from './agentLog.js'
export type { AgentEffect, AgentEffectHandler } from './effects.js'
export { createAgentClient } from './factory.js'
export type { CreateAgentClientOpts, AgentClient } from './factory.js'
export { summarizeDiff, groupDiff, describeOp } from './diff-render.js'
export type { DiffGroup } from './diff-render.js'
